
rgs = {
'acidhouse': ['acid house', 'acid techno', 'acidcore', 'acid trance','acid idm'],
'ambientmusic': ["ambient house", "ambient idm", "ambient techno", "deep ambient", "drone ambient"],
'AStateOfTrance': ["trance", "uplifting trance", "progressive trance", "progressive uplifting trance", "progressive trance house", "deep uplifting trance", "tech trance", "acid trance"],
'AtmosphericDnB': ['drum and bass', "dancefloor dnb", "uk dnb", "dutch dnb", "atmospheric dnb", "deep dnb", "minimal dnb"],
'BigBeat': ['big beat'], 
'boogiemusic': ['boogie'],
'breakbeat': ['breakbeat'],
'breakcore': ['breakcore'],
'chicagohouse': ['chicago house'],
'chillout': ['chill out'],
'complextro': ['complextro'],
'darkstep': ['darkstep'],
'deephouse': ["deep house", "deep deep house"],
'DnB': ['drum and bass', "dancefloor dnb", "uk dnb", "dutch dnb", "atmospheric dnb", "deep dnb", "minimal dnb"],
'DubStep': ["melodic dubstep", "dubstep", "dub", "gaming dubstep", "classic dubstep", "dub techno", "minimal dub", "deep dubstep", "electro dub", "french dub", "experimental dub", "minimal dubstep", "ambient dub techno", "experimental dubstep", "dubstep product", "cinematic dubstep"],
'EDM': ["edm", "pop edm", "gaming edm", "deep pop edm"],
'EBM': ['ebm'],
'electronicdancemusic': ["dance pop", "deep dance pop"],
'ElectronicJazz': ['electro jazz'],
'ElectronicBlues': ['electric blues'],
'electrohiphop': ['trip hop'],
'electrohouse': ['electro house', 'progressive electro house'],
'electronicmagic': ['edm', 'idm'],
'ElectronicMusic': ["electropop", "electro house", "electronica", "progressive electro house", "electronic trap", "electric blues", "swedish electropop", "electro", "electro latino", "electra", "indie electropop", "pop electronico", "japanese electropop", "electro-pop francais", "electropowerpop", "electro swing", "organic electronic", "uk experimental electronic", "vintage french electronic", "electric bass", "dark electro", "indie electronica", "experimental electronic", "nu electro", "dark electro-industrial"] ,
'electropop': ['electropop'],
'electroswing': ['electro swing'],
'ExperimentalMusic': ['experimental',"uk experimental electronic", "experimental electronic"],
'frenchelectro': ['vintage french electronic', 'french indietronica', 'french synthpop', 'french tech house'],
'frenchhouse': ['vintage french electronic', 'french indietronica', 'french synthpop', 'french tech house'],
'funkhouse': ["funky tech house", "funky house", "deep funk house"], 
'fusiondancemusic': ["progressive jazz fusion", "psychedelic jazz fusion", "deep downtempo fusion", "ambient fusion", "downtempo fusion", "deep jazz fusion"],
'futurebeats': ["future bass", "future house", "future funk", "future garage"],
'FutureFunkAirlines': ["future bass", "future house", "future funk", "future garage", "funky tech house", "funky house", "deep funk house"], 
'FutureGarage': ['future garage'],
'futuresynth': ["synthpop", "neo-synthpop", "french synthpop", "swedish synthpop", "synthwave", "synth funk", "chillsynth", "darksynth", "synthesizer", "experimental synth", "minimal synth", "deep neo-synthpop"],
'glitch': ["glitchcore", "glitch hop", "glitch", "glitchbreak", "glitch pop", "glitch beats"],
'glitchop': ["glitchcore", "glitch hop", "glitch", "glitchbreak", "glitch pop", "glitch beats"],
'Grime': ['grime', 'grimewave', 'instrumental grime'],
'happyhardcore': ["happy hardcore", "deep happy hardcore"],
'hardhouse': ['hard house'],
'hardstyle': ['hardstyle'],
'house': ['house'],
'idm': ["ambient idm", "deep idm", "abstract idm", "japanese idm", "acid idm"],
'industrialmusic': ["industrial", "electro-industrial", "industrial techno", "ambient industrial", "industrial hardcore", "dark electro-industrial"],
'ItaloDisco': ["italo dance", "italo house", "italogaze", "deep italo disco", "italo beats"],
'latinhouse': ['latin house', 'latin tech house'],
'LiquidDubstep': ["liquid funk", "deep liquid bass", "deep liquid"],
'mashups': ['mashup'],
'melodichouse': ['melodic techno'],
'minimal': ["minimal techno", "minimal tech house", "post-minimalism", "minimalism", "high-tech minimal", "deep minimal techno", "minimal dub", "minimal wave", "minimal melodic techno", "minimal dnb", "hard minimal techno", "minimal dubstep", "dark minimal techno", "minimal synth"],
'nightstep': ['nightrun', 'nightcore'],
'OldskoolRave': ["new rave", "rave funk", "rave", "techno rave"],
'Outrun': ["synthpop", "neo-synthpop", "french synthpop", "synthwave", "chillsynth", "darksynth", "synthesizer", "early synthpop", "synth punk", "modular synth", "experimental synth", "minimal synth", "synthetic classical", "deep neo-synthpop"],
'theOverload': ['electronic', 'ebm','noise', 'detroit house', 'detroit techno', 'chicago house', 'lo-fi', 'house', 'techno'],
'plunderphonics': ['plunderphonics'],
'psybient': ["psychill" "ambient psychill" "experimental psych" "psytech" "deep psytrance" "deep darkpsy"],
'PsyBreaks': ['psybreaks'],
'psytrance': ["progressive psytrance", "dark psytrance", "deep psytrance", "goa psytrance"],
'purplemusic': ['purple sound'],
'raggajungle': ['ragga jungle', 'deep ragga'],
'RealDubstep': ["melodic dubstep", "dubstep", "gaming dubstep", "classic dubstep", "deep dubstep", "riddim dubstep", "dubsteppe", "minimal dubstep", "experimental dubstep", "dubstep product", "cinematic dubstep"],
'skweee': ['skweee'],
'swinghouse': ['electro swing'],
'tech_house': ["tech house", "minimal tech house", "funky tech house", "uk tech house", "deep tech house", "french tech house", "mexican tech house", "deep deep tech house"],
'Techno': ["german techno", "minimal techno", "hardcore techno", "destroy techno", "dark techno", "melodic techno", "techno", "techno kayo", "deep minimal techno", "italian techno", "french techno", "dub techno", "raw techno", "proto-techno", "scottish techno", "deep techno", "belgian techno", "bleep techno", "minimal melodic techno", "acid techno", "ambient techno", "detroit techno", "hard techno", "berlin minimal techno", "danish techno", "russian techno", "spanish techno", "swedish techno", "techno rave", "hard minimal techno", "israeli techno", "german dark minimal techno", "experimental techno", "industrial techno", "brazilian techno", "hungarian techno", "swiss techno", "japanese techno", "modular techno", "irish techno", "portuguese techno", "austrian techno", "australian techno", "greek techno", "techno argentina", "ambient dub techno", "dark minimal techno", "polish techno", "norwegian techno", "mexican techno", "finnish techno", "deep hardtechno", "somatik techno", "re:techno", "indian techno"],
'Trance': ["trance", "uplifting trance", "progressive trance", "trancecore", "dutch trance", "bubble trance", "psychedelic trance", "german trance", "progressive psytrance", "trance brasileiro", "progressive uplifting trance", "progressive trance house", "dream trance", "deep uplifting trance", "russian trance", "vocal trance", "hard trance", "trance mexicano", "italian trance", "focus trance", "ambient trance", "tech trance", "acid trance", "dark psytrance", "old school hard trance", "deep progressive trance", "deep psytrance", "covertrance", "goa trance", "cosmic uplifting trance", "glitter trance", "goa psytrance", "chill-out trance"],
'tranceandbass': ["trance", "uplifting trance", "progressive trance", "trancecore", "dutch trance", "bubble trance", "psychedelic trance", "german trance", "progressive psytrance", "trance brasileiro", "progressive uplifting trance", "progressive trance house", "dream trance", "deep uplifting trance", "russian trance", "vocal trance", "hard trance", "trance mexicano", "italian trance", "focus trance", "ambient trance", "tech trance", "acid trance", "dark psytrance", "old school hard trance", "deep progressive trance", "deep psytrance", "covertrance", "goa trance", "cosmic uplifting trance", "glitter trance", "goa psytrance", "chill-out trance"],
'trap': ['trap'],
'tribalbeats': ['tribal house'],
'TropicalHouse': ["tropical house", "tropical", "deep tropical house"],
'ukfunky': ['uk funky'],
'witch_house': ['witch house'],
}
